name: d-namic
favicon: null
layout_spectrum: 0.25337
typography_spectrum: 0.1305
title: 'd-namic incubator&accelerator'
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ff9300'
    - '#ff0000'
    - '#ff8000'
    - '#ff4000'
    - '#ff5500'
  brandStrength: 0
  lightness: 1
  saturation: 0.625
  rhythmicContrast: 1
purpose: []
